global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'galeos-dashboard'
    static_configs:
      - targets: ['localhost:9000'] # O Prometheus acessa o exportador via localhost dentro do mesmo container.
